spring:
  datasource:
    # Notice the port is strictly 6543 and no query parameters at the end!
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres
    # You MUST use this extended username for the pooler
    username: postgres.qrhyeydljnbjklsdvyls
    # Your real password goes here
    password: YourActualPasswordHere
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true